export const SET_PROJECT_LIST = "SET_PROJECT_LIST";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const FILTER_PROJECT = "FILTER_PROJECT";
export const SET_MEMBER_INFO = "SET_MEMBER_INFO";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";

export const GET_ALL_MEMBER = "GET_ALL_MEMBER";
export const GET_USER_BY_PROJECTID = "GET_USER_BY_PROJECTID";
export const DELETE_MEMBER_PROJECT = "DELETE_MEMBER_PROJECT";

export const SET_PROJECT_DETAIL_ARR = "SET_PROJECT_DETAIL_ARR";
