export const SET_PROJECT_LIST = 'SET_PROJECT_LIST'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const FILTER_PROJECT = 'FILTER_PROJECT'
export const SET_MEMBER_INFO = 'SET_MEMBER_INFO'
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const GET_ALL_MEMBER = 'GET_ALL_MEMBER'

//PROJECT_DETAILS
export const GET_USER_BY_PROJECTID = 'GET_USER_BY_PROJECTID'
export const DELETE_MEMBER_PROJECT = 'DELETE_MEMBER_PROJECT'
export const SET_PROJECT_DETAIL_ARR = 'SET_PROJECT_DETAIL_ARR'

//MEMBER
export const ADD_MEMBER_BOARD = 'ADD_MEMBER_BOARD'
export const REMOVE_MEMBER_BOARD = 'REMOVE_MEMBER_BOARD'
export const SEARCH_MEMBER_BOARD = 'SEARCH_MEMBER_BOARD'
export const SET_TASKDETAIL = 'SET_TASKDETAIL'

//COMMENT
export const SET_COMMENT_ALL = 'SET_COMMENT_ALL'
export const INSERT_COMMENT = 'INSERT_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const SET_DESCRIPTION = 'SET_DESCRIPTION'
